apiVersion: v1
kind: Pod
metadeta: 
  name: postgres-pod
  labels: 
    name: postgres-pod 
    app: demo-voting-app

spec:
  containers: 
  - name: postgres
    image: postgres:9.4
    ports: 
    - containerPort: 5432
